name: Build and Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build Package 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
        
      - name: Set up .NET Core 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Give access to private nugets
        run: dotnet nuget add source --username ocb-dev-04 --password ${{ secrets.NUGET_AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ocb-dev-04/index.json"
      
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Run signing script
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        run: |
          chmod +x ./scripts/pack_and_sign.sh
          ./scripts/pack_and_sign.sh

      - name: Publish
        run: >
          dotnet nuget push ./scripts/OCB.Mediator.Helper.${{ github.ref_name}}.nupkg -s https://nuget.pkg.github.com/ocb-dev-04/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
